account_move_base_import: ensure the filename is captured properly when a file is uploaded:
It was causing the error below:

File "/odoo/external-src/account-reconcile/account_move_base_import/wizard/import_statement.py", line 53, in _check_extension
(__, ftype) = os.path.splitext(self.file_name)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "<frozen posixpath>", line 118, in splitext
TypeError: expected str, bytes or os.PathLike object, not bool